import Head from 'next/head'
import Layout from "../components/Layout"

export default function About() {
    return (
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className="text-sm space-y-1 tracking-wider">
                <h2>Tentang saya</h2>
                <p>Saya merupakan programmer dengan mengawali karir sebagai <strong>Java developer selama 2 tahun</strong>, untuk saat ini saya lebih menyukai menjadi <strong>Front end developer</strong> yang selalu berurusan dengan ide-ide baru, terutama didalam hal user interface sehingga membuat saya lebih tertantang dan berkembang. walaupun baru dibidang ini tetapi itu merupakan hal yang luar biasa bagi, saya karena dapat keluar dari zona nyaman dan bisa survive sampai saat ini.</p>
                <p>Tentu tidak lah mudah untuk sampai ketitik saat ini, karena banyak hal yang harus dilalui, mulai dari belajar memanage waktu, belajar bekerja sama dengan tim, bahkan terkadang harus berada di posisi sebagai leader. semua itu sudah pernah saya alami dan rasakan</p>
                <p> Terkesan pekerjaan ini memang menbutuhkan konsisten yang sangat tinggi dan tidak mengenal lelah, dengan demikian tujuan akhir untuk selalu konsisten berbuat kebaikan sehingga bermanfaat bagi orang lain</p>
            </section>
        </>

    )
}

About.getLayout = function getLayout(page) {
    return (
        <Layout>
            {page}
        </Layout>
    )
}